name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure fetching all historical commits
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Pull latest changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main --rebase
      - name: Commit & Push
        run: |
          git add -A .
          if git commit -m "generated"; then
            git push
          else
            echo "No changes to commit"